map:
  filename: opk-map.png
  resolution: 0.1

obstacles:
  - type: circle
    center_x: 10.0
    center_y: 12.0
    radius: 2.5
  - type: rectangle
    x: 20.0
    y: 21.0
    width: 4.0
    height: 3.0

station:
  x: 30.0
  y: 40.0
  radius: 20.0

robot:
  radius: 1.0
  max_capacity: 10

waste:
  radius:
    min: 1.0
    max: 3.0
  types:
    - name: sklo
      color: green
    - name: papier
      color: blue
    - name: plast
      color: yellow
