map:
  filename: opk-map.png
  resolution: 0.1

obstacles:
  - type: circle
    center_x: 40.0
    center_y: 60.0
    radius: 2.5
  - type: rectangle
    x: 60.0
    y: 40.0
    width: 4.0
    height: 3.0

station:
  x: 40.0
  y: 50.0
  radius: 5.0

robot:
  radius: 1.0
  max_capacity: 5

waste:
  radius:
    min: 1.0
    max: 3.0
  types:
    - name: sklo
      color: green
    - name: papier
      color: blue
    - name: plast
      color: yellow

game:
  keep_clean:
    waves: 3
    waste_per_wave: 5
    required_per_wave: 5
    wave_time_limit_seconds: 60
    result_file: keep_clean_result.txt
