map:
  filename: opk-map.png
  resolution: 0.1

obstacles:
  - type: circle
    center_x: 10.0
    center_y: 12.0
    radius: 2.5
  - type: rectangle
    x: 20.0
    y: 21.0
    width: 4.0
    height: 3.0

waste_station:
  x: 30.0
  y: 40.0
  width: 3.0
  height: 3.0
